Dumping 8 rows from Peak Margin grid:
2025-09-05 18:13:37,184 [INFO] Row 0: ["<Error:'function' object has no attribute 'get'>", "<Error:'function' object has no attribute 'get'>", "<Error:'function' object has no attribute 'get'>", "<Error:'function' object has no attribute 'get'>", "<Error:'function' object has no attribute 'get'>", "<Error:'function' object has no attribute 'get'>", "<Error:'function' object has no attribute 'get'>", "<Error:'function' object has no attribute 'get'>", "<Error:'function' object has no attribute 'get'>"]
2025-09-05 18:13:37,184 [INFO] Row 1: ["<Error:'function' object has no attribute 'get'>", "<Error:'function' object has no attribute 'get'>", "<Error:'function' object has no attribute 'get'>", "<Error:'function' object has no attribute 'get'>", "<Error:'function' object has no attribute 'get'>", "<Error:'function' object has no attribute 'get'>", "<Error:'function' object has no attribute 'get'>", "<Error:'function' object has no attribute 'get'>", "<Error:'function' object has no attribute 'get'>"]
2025-09-05 18:13:37,200 [INFO] Row 2: ["<Error:'function' object has no attribute 'get'>", "<Error:'function' object has no attribute 'get'>", "<Error:'function' object has no attribute 'get'>", "<Error:'function' object has no attribute 'get'>", "<Error:'function' object has no attribute 'get'>", "<Error:'function' object has no attribute 'get'>", "<Error:'function' object has no attribute 'get'>", "<Error:'function' object has no attribute 'get'>", "<Error:'function' object has no attribute 'get'>"]
2025-09-05 18:13:37,200 [INFO] Row 3: ["<Error:'function' object has no attribute 'get'>", "<Error:'function' object has no attribute 'get'>", "<Error:'function' object has no attribute 'get'>", "<Error:'function' object has no attribute 'get'>", "<Error:'function' object has no attribute 'get'>", "<Error:'function' object has no attribute 'get'>", "<Error:'function' object has no attribute 'get'>", "<Error:'function' object has no attribute 'get'>", "<Error:'function' object has no attribute 'get'>"]
2025-09-05 18:13:37,200 [INFO] Row 4: ["<Error:'function' object has no attribute 'get'>", "<Error:'function' object has no attribute 'get'>", "<Error:'function' object has no attribute 'get'>", "<Error:'function' object has no attribute 'get'>", "<Error:'function' object has no attribute 'get'>", "<Error:'function' object has no attribute 'get'>", "<Error:'function' object has no attribute 'get'>", "<Error:'function' object has no attribute 'get'>", "<Error:'function' object has no attribute 'get'>"]
2025-09-05 18:13:37,200 [INFO] Row 5: ["<Error:'function' object has no attribute 'get'>", "<Error:'function' object has no attribute 'get'>", "<Error:'function' object has no attribute 'get'>", "<Error:'function' object has no attribute 'get'>", "<Error:'function' object has no attribute 'get'>", "<Error:'function' object has no attribute 'get'>", "<Error:'function' object has no attribute 'get'>", "<Error:'function' object has no attribute 'get'>", "<Error:'function' object has no attribute 'get'>"]
2025-09-05 18:13:37,200 [INFO] Row 6: ["<Error:'function' object has no attribute 'get'>", "<Error:'function' object has no attribute 'get'>", "<Error:'function' object has no attribute 'get'>", "<Error:'function' object has no attribute 'get'>", "<Error:'function' object has no attribute 'get'>", "<Error:'function' object has no attribute 'get'>", "<Error:'function' object has no attribute 'get'>", "<Error:'function' object has no attribute 'get'>", "<Error:'function' object has no attribute 'get'>"]
2025-09-05 18:13:37,200 [INFO] Row 7: ["<Error:'function' object has no attribute 'get'>", "<Error:'function' object has no attribute 'get'>", "<Error:'function' object has no attribute 'get'>", "<Error:'function' object has no attribute 'get'>", "<Error:'function' object has no attribute 'get'>", "<Error:'function' object has no attribute 'get'>", "<Error:'function' object has no attribute 'get'>", "<Error:'function' object has no attribute 'get'>", "<Error:'function' object has no attribute 'get'>"]
2025-09-05 18:13:41,013 [INFO] Found 8 rows, scanning for start_time...
2025-09-05 18:13:45,810 [INFO] Found 8 rows, scanning for start_time...
2025-09-05 18:13:50,765 [INFO] Found 8 rows, scanning for start_time...
2025-09-05 18:13:55,594 [INFO] Found 8 rows, scanning for start_time...
2025-09-05 18:14:00,407 [INFO] Found 8 rows, scanning for start_time...
2025-09-05 18:14:01,407 [ERROR] No row found with Start Time = 17:06:00 within 20s
2025-09-05 18:14:01,407 [ERROR] Automation failed: No row found with Start Time = 17:06:00 within 20s
Traceback (most recent call last):
  File "C:\Users\Test3\Desktop\automation\rms\test-case_pywinauto9.py", line 350, in main
    run_workflow_for_user("rash1", "change@1212", is_rash1=True, start_time_value=start_time_value)
  File "C:\Users\Test3\Desktop\automation\rms\test-case_pywinauto9.py", line 338, in run_workflow_for_user
    handle_peak_margin_reject_for_rash1(app, main_win, start_time_value)
  File "C:\Users\Test3\Desktop\automation\rms\test-case_pywinauto9.py", line 291, in handle_peak_margin_reject_for_rash1
    raise RuntimeError(msg)
RuntimeError: No row found with Start Time = 17:06:00 within 20s
